# See https://pre-commit.com for more information
repos:
  # Local hooks
  - repo: local
    hooks:
      - id: show-python-version
        name: Show Python version
        entry: python --version
        language: system
        pass_filenames: false

  # Basic sanity checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements

  # Ruff (lint + format)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Mypy (static type checking)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive]
        additional_dependencies:
          - numpy
          - click
          - pydantic
          - pydantic-settings
          - pytest
          - pytest-asyncio

  # Bandit (security checks)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
